spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: t.dev3.team@gmail.com
    password: tljsbgbdzdxzwuki
    properties:
      mail:
        smtp:
          timeout: 5000
          auth: true
          starttls:
            enable: true




shop:
  active-value: core-local